/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/dashboard/transaction/index'
import { Route as DashboardSimcardIndexRouteImport } from './routes/dashboard/simcard/index'
import { Route as DashboardProductIndexRouteImport } from './routes/dashboard/product/index'
import { Route as DashboardProductVariantIndexRouteImport } from './routes/dashboard/product-variant/index'
import { Route as DashboardProductAccountIndexRouteImport } from './routes/dashboard/product-account/index'
import { Route as DashboardProductAccountUserIndexRouteImport } from './routes/dashboard/product-account-user/index'
import { Route as DashboardPlatformIndexRouteImport } from './routes/dashboard/platform/index'
import { Route as DashboardPlatformProductIndexRouteImport } from './routes/dashboard/platform-product/index'
import { Route as DashboardEwalletIndexRouteImport } from './routes/dashboard/ewallet/index'
import { Route as DashboardEwalletTypeIndexRouteImport } from './routes/dashboard/ewallet-type/index'
import { Route as DashboardEwalletTopupIndexRouteImport } from './routes/dashboard/ewallet-topup/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/dashboard/email/index'
import { Route as DashboardDeviceIndexRouteImport } from './routes/dashboard/device/index'
import { Route as DashboardTransactionAddRouteImport } from './routes/dashboard/transaction/add'
import { Route as DashboardSimcardAddRouteImport } from './routes/dashboard/simcard/add'
import { Route as DashboardProductAddRouteImport } from './routes/dashboard/product/add'
import { Route as DashboardProductVariantAddRouteImport } from './routes/dashboard/product-variant/add'
import { Route as DashboardProductAccountAddRouteImport } from './routes/dashboard/product-account/add'
import { Route as DashboardProductAccountUserAddRouteImport } from './routes/dashboard/product-account-user/add'
import { Route as DashboardPlatformAddRouteImport } from './routes/dashboard/platform/add'
import { Route as DashboardPlatformProductAddRouteImport } from './routes/dashboard/platform-product/add'
import { Route as DashboardEwalletAddRouteImport } from './routes/dashboard/ewallet/add'
import { Route as DashboardEwalletTypeAddRouteImport } from './routes/dashboard/ewallet-type/add'
import { Route as DashboardEwalletTopupAddRouteImport } from './routes/dashboard/ewallet-topup/add'
import { Route as DashboardEmailAddRouteImport } from './routes/dashboard/email/add'
import { Route as DashboardDeviceAddRouteImport } from './routes/dashboard/device/add'
import { Route as DashboardSimcardSimcardIdEditRouteImport } from './routes/dashboard/simcard/$simcardId.edit'
import { Route as DashboardProductProductIdEditRouteImport } from './routes/dashboard/product/$productId.edit'
import { Route as DashboardProductVariantProductVariantIdEditRouteImport } from './routes/dashboard/product-variant/$productVariantId.edit'
import { Route as DashboardProductAccountProductAccountIdEditRouteImport } from './routes/dashboard/product-account/$productAccountId.edit'
import { Route as DashboardProductAccountUserProductAccountUserIdEditRouteImport } from './routes/dashboard/product-account-user/$productAccountUserId.edit'
import { Route as DashboardPlatformPlatformIdEditRouteImport } from './routes/dashboard/platform/$platformId.edit'
import { Route as DashboardPlatformProductPlatformProductIdEditRouteImport } from './routes/dashboard/platform-product/$platformProductId.edit'
import { Route as DashboardEwalletEwalletIdEditRouteImport } from './routes/dashboard/ewallet/$ewalletId.edit'
import { Route as DashboardEwalletTypeEwalletTypeIdEditRouteImport } from './routes/dashboard/ewallet-type/$ewalletTypeId.edit'
import { Route as DashboardEwalletTopupEwalletTopupIdEditRouteImport } from './routes/dashboard/ewallet-topup/$ewalletTopupId.edit'
import { Route as DashboardEmailEmailIdEditRouteImport } from './routes/dashboard/email/$emailId.edit'
import { Route as DashboardDeviceDeviceIdEditRouteImport } from './routes/dashboard/device/$deviceId.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSimcardIndexRoute = DashboardSimcardIndexRouteImport.update({
  id: '/simcard/',
  path: '/simcard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductVariantIndexRoute =
  DashboardProductVariantIndexRouteImport.update({
    id: '/product-variant/',
    path: '/product-variant/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountIndexRoute =
  DashboardProductAccountIndexRouteImport.update({
    id: '/product-account/',
    path: '/product-account/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountUserIndexRoute =
  DashboardProductAccountUserIndexRouteImport.update({
    id: '/product-account-user/',
    path: '/product-account-user/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformIndexRoute = DashboardPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductIndexRoute =
  DashboardPlatformProductIndexRouteImport.update({
    id: '/platform-product/',
    path: '/platform-product/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletIndexRoute = DashboardEwalletIndexRouteImport.update({
  id: '/ewallet/',
  path: '/ewallet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEwalletTypeIndexRoute =
  DashboardEwalletTypeIndexRouteImport.update({
    id: '/ewallet-type/',
    path: '/ewallet-type/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletTopupIndexRoute =
  DashboardEwalletTopupIndexRouteImport.update({
    id: '/ewallet-topup/',
    path: '/ewallet-topup/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDeviceIndexRoute = DashboardDeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionAddRoute = DashboardTransactionAddRouteImport.update({
  id: '/transaction/add',
  path: '/transaction/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSimcardAddRoute = DashboardSimcardAddRouteImport.update({
  id: '/simcard/add',
  path: '/simcard/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductAddRoute = DashboardProductAddRouteImport.update({
  id: '/product/add',
  path: '/product/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductVariantAddRoute =
  DashboardProductVariantAddRouteImport.update({
    id: '/product-variant/add',
    path: '/product-variant/add',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountAddRoute =
  DashboardProductAccountAddRouteImport.update({
    id: '/product-account/add',
    path: '/product-account/add',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountUserAddRoute =
  DashboardProductAccountUserAddRouteImport.update({
    id: '/product-account-user/add',
    path: '/product-account-user/add',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformAddRoute = DashboardPlatformAddRouteImport.update({
  id: '/platform/add',
  path: '/platform/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductAddRoute =
  DashboardPlatformProductAddRouteImport.update({
    id: '/platform-product/add',
    path: '/platform-product/add',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletAddRoute = DashboardEwalletAddRouteImport.update({
  id: '/ewallet/add',
  path: '/ewallet/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEwalletTypeAddRoute = DashboardEwalletTypeAddRouteImport.update({
  id: '/ewallet-type/add',
  path: '/ewallet-type/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEwalletTopupAddRoute =
  DashboardEwalletTopupAddRouteImport.update({
    id: '/ewallet-topup/add',
    path: '/ewallet-topup/add',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailAddRoute = DashboardEmailAddRouteImport.update({
  id: '/email/add',
  path: '/email/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDeviceAddRoute = DashboardDeviceAddRouteImport.update({
  id: '/device/add',
  path: '/device/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSimcardSimcardIdEditRoute =
  DashboardSimcardSimcardIdEditRouteImport.update({
    id: '/simcard/$simcardId/edit',
    path: '/simcard/$simcardId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductProductIdEditRoute =
  DashboardProductProductIdEditRouteImport.update({
    id: '/product/$productId/edit',
    path: '/product/$productId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductVariantProductVariantIdEditRoute =
  DashboardProductVariantProductVariantIdEditRouteImport.update({
    id: '/product-variant/$productVariantId/edit',
    path: '/product-variant/$productVariantId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountProductAccountIdEditRoute =
  DashboardProductAccountProductAccountIdEditRouteImport.update({
    id: '/product-account/$productAccountId/edit',
    path: '/product-account/$productAccountId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductAccountUserProductAccountUserIdEditRoute =
  DashboardProductAccountUserProductAccountUserIdEditRouteImport.update({
    id: '/product-account-user/$productAccountUserId/edit',
    path: '/product-account-user/$productAccountUserId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformPlatformIdEditRoute =
  DashboardPlatformPlatformIdEditRouteImport.update({
    id: '/platform/$platformId/edit',
    path: '/platform/$platformId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformProductPlatformProductIdEditRoute =
  DashboardPlatformProductPlatformProductIdEditRouteImport.update({
    id: '/platform-product/$platformProductId/edit',
    path: '/platform-product/$platformProductId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletEwalletIdEditRoute =
  DashboardEwalletEwalletIdEditRouteImport.update({
    id: '/ewallet/$ewalletId/edit',
    path: '/ewallet/$ewalletId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletTypeEwalletTypeIdEditRoute =
  DashboardEwalletTypeEwalletTypeIdEditRouteImport.update({
    id: '/ewallet-type/$ewalletTypeId/edit',
    path: '/ewallet-type/$ewalletTypeId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEwalletTopupEwalletTopupIdEditRoute =
  DashboardEwalletTopupEwalletTopupIdEditRouteImport.update({
    id: '/ewallet-topup/$ewalletTopupId/edit',
    path: '/ewallet-topup/$ewalletTopupId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailEmailIdEditRoute =
  DashboardEmailEmailIdEditRouteImport.update({
    id: '/email/$emailId/edit',
    path: '/email/$emailId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDeviceDeviceIdEditRoute =
  DashboardDeviceDeviceIdEditRouteImport.update({
    id: '/device/$deviceId/edit',
    path: '/device/$deviceId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/device/add': typeof DashboardDeviceAddRoute
  '/dashboard/email/add': typeof DashboardEmailAddRoute
  '/dashboard/ewallet-topup/add': typeof DashboardEwalletTopupAddRoute
  '/dashboard/ewallet-type/add': typeof DashboardEwalletTypeAddRoute
  '/dashboard/ewallet/add': typeof DashboardEwalletAddRoute
  '/dashboard/platform-product/add': typeof DashboardPlatformProductAddRoute
  '/dashboard/platform/add': typeof DashboardPlatformAddRoute
  '/dashboard/product-account-user/add': typeof DashboardProductAccountUserAddRoute
  '/dashboard/product-account/add': typeof DashboardProductAccountAddRoute
  '/dashboard/product-variant/add': typeof DashboardProductVariantAddRoute
  '/dashboard/product/add': typeof DashboardProductAddRoute
  '/dashboard/simcard/add': typeof DashboardSimcardAddRoute
  '/dashboard/transaction/add': typeof DashboardTransactionAddRoute
  '/dashboard/device': typeof DashboardDeviceIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/ewallet-topup': typeof DashboardEwalletTopupIndexRoute
  '/dashboard/ewallet-type': typeof DashboardEwalletTypeIndexRoute
  '/dashboard/ewallet': typeof DashboardEwalletIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/platform': typeof DashboardPlatformIndexRoute
  '/dashboard/product-account-user': typeof DashboardProductAccountUserIndexRoute
  '/dashboard/product-account': typeof DashboardProductAccountIndexRoute
  '/dashboard/product-variant': typeof DashboardProductVariantIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/simcard': typeof DashboardSimcardIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/device/$deviceId/edit': typeof DashboardDeviceDeviceIdEditRoute
  '/dashboard/email/$emailId/edit': typeof DashboardEmailEmailIdEditRoute
  '/dashboard/ewallet-topup/$ewalletTopupId/edit': typeof DashboardEwalletTopupEwalletTopupIdEditRoute
  '/dashboard/ewallet-type/$ewalletTypeId/edit': typeof DashboardEwalletTypeEwalletTypeIdEditRoute
  '/dashboard/ewallet/$ewalletId/edit': typeof DashboardEwalletEwalletIdEditRoute
  '/dashboard/platform-product/$platformProductId/edit': typeof DashboardPlatformProductPlatformProductIdEditRoute
  '/dashboard/platform/$platformId/edit': typeof DashboardPlatformPlatformIdEditRoute
  '/dashboard/product-account-user/$productAccountUserId/edit': typeof DashboardProductAccountUserProductAccountUserIdEditRoute
  '/dashboard/product-account/$productAccountId/edit': typeof DashboardProductAccountProductAccountIdEditRoute
  '/dashboard/product-variant/$productVariantId/edit': typeof DashboardProductVariantProductVariantIdEditRoute
  '/dashboard/product/$productId/edit': typeof DashboardProductProductIdEditRoute
  '/dashboard/simcard/$simcardId/edit': typeof DashboardSimcardSimcardIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/device/add': typeof DashboardDeviceAddRoute
  '/dashboard/email/add': typeof DashboardEmailAddRoute
  '/dashboard/ewallet-topup/add': typeof DashboardEwalletTopupAddRoute
  '/dashboard/ewallet-type/add': typeof DashboardEwalletTypeAddRoute
  '/dashboard/ewallet/add': typeof DashboardEwalletAddRoute
  '/dashboard/platform-product/add': typeof DashboardPlatformProductAddRoute
  '/dashboard/platform/add': typeof DashboardPlatformAddRoute
  '/dashboard/product-account-user/add': typeof DashboardProductAccountUserAddRoute
  '/dashboard/product-account/add': typeof DashboardProductAccountAddRoute
  '/dashboard/product-variant/add': typeof DashboardProductVariantAddRoute
  '/dashboard/product/add': typeof DashboardProductAddRoute
  '/dashboard/simcard/add': typeof DashboardSimcardAddRoute
  '/dashboard/transaction/add': typeof DashboardTransactionAddRoute
  '/dashboard/device': typeof DashboardDeviceIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/ewallet-topup': typeof DashboardEwalletTopupIndexRoute
  '/dashboard/ewallet-type': typeof DashboardEwalletTypeIndexRoute
  '/dashboard/ewallet': typeof DashboardEwalletIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/platform': typeof DashboardPlatformIndexRoute
  '/dashboard/product-account-user': typeof DashboardProductAccountUserIndexRoute
  '/dashboard/product-account': typeof DashboardProductAccountIndexRoute
  '/dashboard/product-variant': typeof DashboardProductVariantIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/simcard': typeof DashboardSimcardIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/device/$deviceId/edit': typeof DashboardDeviceDeviceIdEditRoute
  '/dashboard/email/$emailId/edit': typeof DashboardEmailEmailIdEditRoute
  '/dashboard/ewallet-topup/$ewalletTopupId/edit': typeof DashboardEwalletTopupEwalletTopupIdEditRoute
  '/dashboard/ewallet-type/$ewalletTypeId/edit': typeof DashboardEwalletTypeEwalletTypeIdEditRoute
  '/dashboard/ewallet/$ewalletId/edit': typeof DashboardEwalletEwalletIdEditRoute
  '/dashboard/platform-product/$platformProductId/edit': typeof DashboardPlatformProductPlatformProductIdEditRoute
  '/dashboard/platform/$platformId/edit': typeof DashboardPlatformPlatformIdEditRoute
  '/dashboard/product-account-user/$productAccountUserId/edit': typeof DashboardProductAccountUserProductAccountUserIdEditRoute
  '/dashboard/product-account/$productAccountId/edit': typeof DashboardProductAccountProductAccountIdEditRoute
  '/dashboard/product-variant/$productVariantId/edit': typeof DashboardProductVariantProductVariantIdEditRoute
  '/dashboard/product/$productId/edit': typeof DashboardProductProductIdEditRoute
  '/dashboard/simcard/$simcardId/edit': typeof DashboardSimcardSimcardIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/device/add': typeof DashboardDeviceAddRoute
  '/dashboard/email/add': typeof DashboardEmailAddRoute
  '/dashboard/ewallet-topup/add': typeof DashboardEwalletTopupAddRoute
  '/dashboard/ewallet-type/add': typeof DashboardEwalletTypeAddRoute
  '/dashboard/ewallet/add': typeof DashboardEwalletAddRoute
  '/dashboard/platform-product/add': typeof DashboardPlatformProductAddRoute
  '/dashboard/platform/add': typeof DashboardPlatformAddRoute
  '/dashboard/product-account-user/add': typeof DashboardProductAccountUserAddRoute
  '/dashboard/product-account/add': typeof DashboardProductAccountAddRoute
  '/dashboard/product-variant/add': typeof DashboardProductVariantAddRoute
  '/dashboard/product/add': typeof DashboardProductAddRoute
  '/dashboard/simcard/add': typeof DashboardSimcardAddRoute
  '/dashboard/transaction/add': typeof DashboardTransactionAddRoute
  '/dashboard/device/': typeof DashboardDeviceIndexRoute
  '/dashboard/email/': typeof DashboardEmailIndexRoute
  '/dashboard/ewallet-topup/': typeof DashboardEwalletTopupIndexRoute
  '/dashboard/ewallet-type/': typeof DashboardEwalletTypeIndexRoute
  '/dashboard/ewallet/': typeof DashboardEwalletIndexRoute
  '/dashboard/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/dashboard/platform/': typeof DashboardPlatformIndexRoute
  '/dashboard/product-account-user/': typeof DashboardProductAccountUserIndexRoute
  '/dashboard/product-account/': typeof DashboardProductAccountIndexRoute
  '/dashboard/product-variant/': typeof DashboardProductVariantIndexRoute
  '/dashboard/product/': typeof DashboardProductIndexRoute
  '/dashboard/simcard/': typeof DashboardSimcardIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/dashboard/device/$deviceId/edit': typeof DashboardDeviceDeviceIdEditRoute
  '/dashboard/email/$emailId/edit': typeof DashboardEmailEmailIdEditRoute
  '/dashboard/ewallet-topup/$ewalletTopupId/edit': typeof DashboardEwalletTopupEwalletTopupIdEditRoute
  '/dashboard/ewallet-type/$ewalletTypeId/edit': typeof DashboardEwalletTypeEwalletTypeIdEditRoute
  '/dashboard/ewallet/$ewalletId/edit': typeof DashboardEwalletEwalletIdEditRoute
  '/dashboard/platform-product/$platformProductId/edit': typeof DashboardPlatformProductPlatformProductIdEditRoute
  '/dashboard/platform/$platformId/edit': typeof DashboardPlatformPlatformIdEditRoute
  '/dashboard/product-account-user/$productAccountUserId/edit': typeof DashboardProductAccountUserProductAccountUserIdEditRoute
  '/dashboard/product-account/$productAccountId/edit': typeof DashboardProductAccountProductAccountIdEditRoute
  '/dashboard/product-variant/$productVariantId/edit': typeof DashboardProductVariantProductVariantIdEditRoute
  '/dashboard/product/$productId/edit': typeof DashboardProductProductIdEditRoute
  '/dashboard/simcard/$simcardId/edit': typeof DashboardSimcardSimcardIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/device/add'
    | '/dashboard/email/add'
    | '/dashboard/ewallet-topup/add'
    | '/dashboard/ewallet-type/add'
    | '/dashboard/ewallet/add'
    | '/dashboard/platform-product/add'
    | '/dashboard/platform/add'
    | '/dashboard/product-account-user/add'
    | '/dashboard/product-account/add'
    | '/dashboard/product-variant/add'
    | '/dashboard/product/add'
    | '/dashboard/simcard/add'
    | '/dashboard/transaction/add'
    | '/dashboard/device'
    | '/dashboard/email'
    | '/dashboard/ewallet-topup'
    | '/dashboard/ewallet-type'
    | '/dashboard/ewallet'
    | '/dashboard/platform-product'
    | '/dashboard/platform'
    | '/dashboard/product-account-user'
    | '/dashboard/product-account'
    | '/dashboard/product-variant'
    | '/dashboard/product'
    | '/dashboard/simcard'
    | '/dashboard/transaction'
    | '/dashboard/device/$deviceId/edit'
    | '/dashboard/email/$emailId/edit'
    | '/dashboard/ewallet-topup/$ewalletTopupId/edit'
    | '/dashboard/ewallet-type/$ewalletTypeId/edit'
    | '/dashboard/ewallet/$ewalletId/edit'
    | '/dashboard/platform-product/$platformProductId/edit'
    | '/dashboard/platform/$platformId/edit'
    | '/dashboard/product-account-user/$productAccountUserId/edit'
    | '/dashboard/product-account/$productAccountId/edit'
    | '/dashboard/product-variant/$productVariantId/edit'
    | '/dashboard/product/$productId/edit'
    | '/dashboard/simcard/$simcardId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/device/add'
    | '/dashboard/email/add'
    | '/dashboard/ewallet-topup/add'
    | '/dashboard/ewallet-type/add'
    | '/dashboard/ewallet/add'
    | '/dashboard/platform-product/add'
    | '/dashboard/platform/add'
    | '/dashboard/product-account-user/add'
    | '/dashboard/product-account/add'
    | '/dashboard/product-variant/add'
    | '/dashboard/product/add'
    | '/dashboard/simcard/add'
    | '/dashboard/transaction/add'
    | '/dashboard/device'
    | '/dashboard/email'
    | '/dashboard/ewallet-topup'
    | '/dashboard/ewallet-type'
    | '/dashboard/ewallet'
    | '/dashboard/platform-product'
    | '/dashboard/platform'
    | '/dashboard/product-account-user'
    | '/dashboard/product-account'
    | '/dashboard/product-variant'
    | '/dashboard/product'
    | '/dashboard/simcard'
    | '/dashboard/transaction'
    | '/dashboard/device/$deviceId/edit'
    | '/dashboard/email/$emailId/edit'
    | '/dashboard/ewallet-topup/$ewalletTopupId/edit'
    | '/dashboard/ewallet-type/$ewalletTypeId/edit'
    | '/dashboard/ewallet/$ewalletId/edit'
    | '/dashboard/platform-product/$platformProductId/edit'
    | '/dashboard/platform/$platformId/edit'
    | '/dashboard/product-account-user/$productAccountUserId/edit'
    | '/dashboard/product-account/$productAccountId/edit'
    | '/dashboard/product-variant/$productVariantId/edit'
    | '/dashboard/product/$productId/edit'
    | '/dashboard/simcard/$simcardId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/device/add'
    | '/dashboard/email/add'
    | '/dashboard/ewallet-topup/add'
    | '/dashboard/ewallet-type/add'
    | '/dashboard/ewallet/add'
    | '/dashboard/platform-product/add'
    | '/dashboard/platform/add'
    | '/dashboard/product-account-user/add'
    | '/dashboard/product-account/add'
    | '/dashboard/product-variant/add'
    | '/dashboard/product/add'
    | '/dashboard/simcard/add'
    | '/dashboard/transaction/add'
    | '/dashboard/device/'
    | '/dashboard/email/'
    | '/dashboard/ewallet-topup/'
    | '/dashboard/ewallet-type/'
    | '/dashboard/ewallet/'
    | '/dashboard/platform-product/'
    | '/dashboard/platform/'
    | '/dashboard/product-account-user/'
    | '/dashboard/product-account/'
    | '/dashboard/product-variant/'
    | '/dashboard/product/'
    | '/dashboard/simcard/'
    | '/dashboard/transaction/'
    | '/dashboard/device/$deviceId/edit'
    | '/dashboard/email/$emailId/edit'
    | '/dashboard/ewallet-topup/$ewalletTopupId/edit'
    | '/dashboard/ewallet-type/$ewalletTypeId/edit'
    | '/dashboard/ewallet/$ewalletId/edit'
    | '/dashboard/platform-product/$platformProductId/edit'
    | '/dashboard/platform/$platformId/edit'
    | '/dashboard/product-account-user/$productAccountUserId/edit'
    | '/dashboard/product-account/$productAccountId/edit'
    | '/dashboard/product-variant/$productVariantId/edit'
    | '/dashboard/product/$productId/edit'
    | '/dashboard/simcard/$simcardId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/': {
      id: '/dashboard/transaction/'
      path: '/transaction'
      fullPath: '/dashboard/transaction'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/simcard/': {
      id: '/dashboard/simcard/'
      path: '/simcard'
      fullPath: '/dashboard/simcard'
      preLoaderRoute: typeof DashboardSimcardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-variant/': {
      id: '/dashboard/product-variant/'
      path: '/product-variant'
      fullPath: '/dashboard/product-variant'
      preLoaderRoute: typeof DashboardProductVariantIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account/': {
      id: '/dashboard/product-account/'
      path: '/product-account'
      fullPath: '/dashboard/product-account'
      preLoaderRoute: typeof DashboardProductAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account-user/': {
      id: '/dashboard/product-account-user/'
      path: '/product-account-user'
      fullPath: '/dashboard/product-account-user'
      preLoaderRoute: typeof DashboardProductAccountUserIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform/': {
      id: '/dashboard/platform/'
      path: '/platform'
      fullPath: '/dashboard/platform'
      preLoaderRoute: typeof DashboardPlatformIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/': {
      id: '/dashboard/platform-product/'
      path: '/platform-product'
      fullPath: '/dashboard/platform-product'
      preLoaderRoute: typeof DashboardPlatformProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet/': {
      id: '/dashboard/ewallet/'
      path: '/ewallet'
      fullPath: '/dashboard/ewallet'
      preLoaderRoute: typeof DashboardEwalletIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-type/': {
      id: '/dashboard/ewallet-type/'
      path: '/ewallet-type'
      fullPath: '/dashboard/ewallet-type'
      preLoaderRoute: typeof DashboardEwalletTypeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-topup/': {
      id: '/dashboard/ewallet-topup/'
      path: '/ewallet-topup'
      fullPath: '/dashboard/ewallet-topup'
      preLoaderRoute: typeof DashboardEwalletTopupIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/': {
      id: '/dashboard/email/'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/device/': {
      id: '/dashboard/device/'
      path: '/device'
      fullPath: '/dashboard/device'
      preLoaderRoute: typeof DashboardDeviceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/add': {
      id: '/dashboard/transaction/add'
      path: '/transaction/add'
      fullPath: '/dashboard/transaction/add'
      preLoaderRoute: typeof DashboardTransactionAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/simcard/add': {
      id: '/dashboard/simcard/add'
      path: '/simcard/add'
      fullPath: '/dashboard/simcard/add'
      preLoaderRoute: typeof DashboardSimcardAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/add': {
      id: '/dashboard/product/add'
      path: '/product/add'
      fullPath: '/dashboard/product/add'
      preLoaderRoute: typeof DashboardProductAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-variant/add': {
      id: '/dashboard/product-variant/add'
      path: '/product-variant/add'
      fullPath: '/dashboard/product-variant/add'
      preLoaderRoute: typeof DashboardProductVariantAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account/add': {
      id: '/dashboard/product-account/add'
      path: '/product-account/add'
      fullPath: '/dashboard/product-account/add'
      preLoaderRoute: typeof DashboardProductAccountAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account-user/add': {
      id: '/dashboard/product-account-user/add'
      path: '/product-account-user/add'
      fullPath: '/dashboard/product-account-user/add'
      preLoaderRoute: typeof DashboardProductAccountUserAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform/add': {
      id: '/dashboard/platform/add'
      path: '/platform/add'
      fullPath: '/dashboard/platform/add'
      preLoaderRoute: typeof DashboardPlatformAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/add': {
      id: '/dashboard/platform-product/add'
      path: '/platform-product/add'
      fullPath: '/dashboard/platform-product/add'
      preLoaderRoute: typeof DashboardPlatformProductAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet/add': {
      id: '/dashboard/ewallet/add'
      path: '/ewallet/add'
      fullPath: '/dashboard/ewallet/add'
      preLoaderRoute: typeof DashboardEwalletAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-type/add': {
      id: '/dashboard/ewallet-type/add'
      path: '/ewallet-type/add'
      fullPath: '/dashboard/ewallet-type/add'
      preLoaderRoute: typeof DashboardEwalletTypeAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-topup/add': {
      id: '/dashboard/ewallet-topup/add'
      path: '/ewallet-topup/add'
      fullPath: '/dashboard/ewallet-topup/add'
      preLoaderRoute: typeof DashboardEwalletTopupAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/add': {
      id: '/dashboard/email/add'
      path: '/email/add'
      fullPath: '/dashboard/email/add'
      preLoaderRoute: typeof DashboardEmailAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/device/add': {
      id: '/dashboard/device/add'
      path: '/device/add'
      fullPath: '/dashboard/device/add'
      preLoaderRoute: typeof DashboardDeviceAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/simcard/$simcardId/edit': {
      id: '/dashboard/simcard/$simcardId/edit'
      path: '/simcard/$simcardId/edit'
      fullPath: '/dashboard/simcard/$simcardId/edit'
      preLoaderRoute: typeof DashboardSimcardSimcardIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/$productId/edit': {
      id: '/dashboard/product/$productId/edit'
      path: '/product/$productId/edit'
      fullPath: '/dashboard/product/$productId/edit'
      preLoaderRoute: typeof DashboardProductProductIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-variant/$productVariantId/edit': {
      id: '/dashboard/product-variant/$productVariantId/edit'
      path: '/product-variant/$productVariantId/edit'
      fullPath: '/dashboard/product-variant/$productVariantId/edit'
      preLoaderRoute: typeof DashboardProductVariantProductVariantIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account/$productAccountId/edit': {
      id: '/dashboard/product-account/$productAccountId/edit'
      path: '/product-account/$productAccountId/edit'
      fullPath: '/dashboard/product-account/$productAccountId/edit'
      preLoaderRoute: typeof DashboardProductAccountProductAccountIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product-account-user/$productAccountUserId/edit': {
      id: '/dashboard/product-account-user/$productAccountUserId/edit'
      path: '/product-account-user/$productAccountUserId/edit'
      fullPath: '/dashboard/product-account-user/$productAccountUserId/edit'
      preLoaderRoute: typeof DashboardProductAccountUserProductAccountUserIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform/$platformId/edit': {
      id: '/dashboard/platform/$platformId/edit'
      path: '/platform/$platformId/edit'
      fullPath: '/dashboard/platform/$platformId/edit'
      preLoaderRoute: typeof DashboardPlatformPlatformIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/$platformProductId/edit': {
      id: '/dashboard/platform-product/$platformProductId/edit'
      path: '/platform-product/$platformProductId/edit'
      fullPath: '/dashboard/platform-product/$platformProductId/edit'
      preLoaderRoute: typeof DashboardPlatformProductPlatformProductIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet/$ewalletId/edit': {
      id: '/dashboard/ewallet/$ewalletId/edit'
      path: '/ewallet/$ewalletId/edit'
      fullPath: '/dashboard/ewallet/$ewalletId/edit'
      preLoaderRoute: typeof DashboardEwalletEwalletIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-type/$ewalletTypeId/edit': {
      id: '/dashboard/ewallet-type/$ewalletTypeId/edit'
      path: '/ewallet-type/$ewalletTypeId/edit'
      fullPath: '/dashboard/ewallet-type/$ewalletTypeId/edit'
      preLoaderRoute: typeof DashboardEwalletTypeEwalletTypeIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ewallet-topup/$ewalletTopupId/edit': {
      id: '/dashboard/ewallet-topup/$ewalletTopupId/edit'
      path: '/ewallet-topup/$ewalletTopupId/edit'
      fullPath: '/dashboard/ewallet-topup/$ewalletTopupId/edit'
      preLoaderRoute: typeof DashboardEwalletTopupEwalletTopupIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/$emailId/edit': {
      id: '/dashboard/email/$emailId/edit'
      path: '/email/$emailId/edit'
      fullPath: '/dashboard/email/$emailId/edit'
      preLoaderRoute: typeof DashboardEmailEmailIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/device/$deviceId/edit': {
      id: '/dashboard/device/$deviceId/edit'
      path: '/device/$deviceId/edit'
      fullPath: '/dashboard/device/$deviceId/edit'
      preLoaderRoute: typeof DashboardDeviceDeviceIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDeviceAddRoute: typeof DashboardDeviceAddRoute
  DashboardEmailAddRoute: typeof DashboardEmailAddRoute
  DashboardEwalletTopupAddRoute: typeof DashboardEwalletTopupAddRoute
  DashboardEwalletTypeAddRoute: typeof DashboardEwalletTypeAddRoute
  DashboardEwalletAddRoute: typeof DashboardEwalletAddRoute
  DashboardPlatformProductAddRoute: typeof DashboardPlatformProductAddRoute
  DashboardPlatformAddRoute: typeof DashboardPlatformAddRoute
  DashboardProductAccountUserAddRoute: typeof DashboardProductAccountUserAddRoute
  DashboardProductAccountAddRoute: typeof DashboardProductAccountAddRoute
  DashboardProductVariantAddRoute: typeof DashboardProductVariantAddRoute
  DashboardProductAddRoute: typeof DashboardProductAddRoute
  DashboardSimcardAddRoute: typeof DashboardSimcardAddRoute
  DashboardTransactionAddRoute: typeof DashboardTransactionAddRoute
  DashboardDeviceIndexRoute: typeof DashboardDeviceIndexRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardEwalletTopupIndexRoute: typeof DashboardEwalletTopupIndexRoute
  DashboardEwalletTypeIndexRoute: typeof DashboardEwalletTypeIndexRoute
  DashboardEwalletIndexRoute: typeof DashboardEwalletIndexRoute
  DashboardPlatformProductIndexRoute: typeof DashboardPlatformProductIndexRoute
  DashboardPlatformIndexRoute: typeof DashboardPlatformIndexRoute
  DashboardProductAccountUserIndexRoute: typeof DashboardProductAccountUserIndexRoute
  DashboardProductAccountIndexRoute: typeof DashboardProductAccountIndexRoute
  DashboardProductVariantIndexRoute: typeof DashboardProductVariantIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardSimcardIndexRoute: typeof DashboardSimcardIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
  DashboardDeviceDeviceIdEditRoute: typeof DashboardDeviceDeviceIdEditRoute
  DashboardEmailEmailIdEditRoute: typeof DashboardEmailEmailIdEditRoute
  DashboardEwalletTopupEwalletTopupIdEditRoute: typeof DashboardEwalletTopupEwalletTopupIdEditRoute
  DashboardEwalletTypeEwalletTypeIdEditRoute: typeof DashboardEwalletTypeEwalletTypeIdEditRoute
  DashboardEwalletEwalletIdEditRoute: typeof DashboardEwalletEwalletIdEditRoute
  DashboardPlatformProductPlatformProductIdEditRoute: typeof DashboardPlatformProductPlatformProductIdEditRoute
  DashboardPlatformPlatformIdEditRoute: typeof DashboardPlatformPlatformIdEditRoute
  DashboardProductAccountUserProductAccountUserIdEditRoute: typeof DashboardProductAccountUserProductAccountUserIdEditRoute
  DashboardProductAccountProductAccountIdEditRoute: typeof DashboardProductAccountProductAccountIdEditRoute
  DashboardProductVariantProductVariantIdEditRoute: typeof DashboardProductVariantProductVariantIdEditRoute
  DashboardProductProductIdEditRoute: typeof DashboardProductProductIdEditRoute
  DashboardSimcardSimcardIdEditRoute: typeof DashboardSimcardSimcardIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDeviceAddRoute: DashboardDeviceAddRoute,
  DashboardEmailAddRoute: DashboardEmailAddRoute,
  DashboardEwalletTopupAddRoute: DashboardEwalletTopupAddRoute,
  DashboardEwalletTypeAddRoute: DashboardEwalletTypeAddRoute,
  DashboardEwalletAddRoute: DashboardEwalletAddRoute,
  DashboardPlatformProductAddRoute: DashboardPlatformProductAddRoute,
  DashboardPlatformAddRoute: DashboardPlatformAddRoute,
  DashboardProductAccountUserAddRoute: DashboardProductAccountUserAddRoute,
  DashboardProductAccountAddRoute: DashboardProductAccountAddRoute,
  DashboardProductVariantAddRoute: DashboardProductVariantAddRoute,
  DashboardProductAddRoute: DashboardProductAddRoute,
  DashboardSimcardAddRoute: DashboardSimcardAddRoute,
  DashboardTransactionAddRoute: DashboardTransactionAddRoute,
  DashboardDeviceIndexRoute: DashboardDeviceIndexRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardEwalletTopupIndexRoute: DashboardEwalletTopupIndexRoute,
  DashboardEwalletTypeIndexRoute: DashboardEwalletTypeIndexRoute,
  DashboardEwalletIndexRoute: DashboardEwalletIndexRoute,
  DashboardPlatformProductIndexRoute: DashboardPlatformProductIndexRoute,
  DashboardPlatformIndexRoute: DashboardPlatformIndexRoute,
  DashboardProductAccountUserIndexRoute: DashboardProductAccountUserIndexRoute,
  DashboardProductAccountIndexRoute: DashboardProductAccountIndexRoute,
  DashboardProductVariantIndexRoute: DashboardProductVariantIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardSimcardIndexRoute: DashboardSimcardIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
  DashboardDeviceDeviceIdEditRoute: DashboardDeviceDeviceIdEditRoute,
  DashboardEmailEmailIdEditRoute: DashboardEmailEmailIdEditRoute,
  DashboardEwalletTopupEwalletTopupIdEditRoute:
    DashboardEwalletTopupEwalletTopupIdEditRoute,
  DashboardEwalletTypeEwalletTypeIdEditRoute:
    DashboardEwalletTypeEwalletTypeIdEditRoute,
  DashboardEwalletEwalletIdEditRoute: DashboardEwalletEwalletIdEditRoute,
  DashboardPlatformProductPlatformProductIdEditRoute:
    DashboardPlatformProductPlatformProductIdEditRoute,
  DashboardPlatformPlatformIdEditRoute: DashboardPlatformPlatformIdEditRoute,
  DashboardProductAccountUserProductAccountUserIdEditRoute:
    DashboardProductAccountUserProductAccountUserIdEditRoute,
  DashboardProductAccountProductAccountIdEditRoute:
    DashboardProductAccountProductAccountIdEditRoute,
  DashboardProductVariantProductVariantIdEditRoute:
    DashboardProductVariantProductVariantIdEditRoute,
  DashboardProductProductIdEditRoute: DashboardProductProductIdEditRoute,
  DashboardSimcardSimcardIdEditRoute: DashboardSimcardSimcardIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
